//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommaApp.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Administrator
    {
        public int AdminID { get; set; }
        public Nullable<int> RoleId { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public System.DateTime UpdatedOn { get; set; }
        public string EmailGUID { get; set; }
        public bool IsConfirmed { get; set; }
        public bool IsActive { get; set; }
    
        public virtual Role Role { get; set; }
    }
}
