//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommaApp.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoleAssignment
    {
        public int Id { get; set; }
        public Nullable<int> RoleId { get; set; }
        public bool IsActive { get; set; }
        public int ModuleId { get; set; }
        public bool IsAdd { get; set; }
        public bool IsEdit { get; set; }
        public bool IsDelete { get; set; }
        public bool IsView { get; set; }
        public bool IsEnable { get; set; }
        public int UserTypeId { get; set; }
    
        public virtual Module Module { get; set; }
        public virtual Role Role { get; set; }
        public virtual UserType UserType { get; set; }
    }
}
