//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommaApp.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserType
    {
        public UserType()
        {
            this.RoleAssignments = new HashSet<RoleAssignment>();
            this.Users = new HashSet<User>();
        }
    
        public int UserTypeId { get; set; }
        public string UserTypeName { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public bool IsActive { get; set; }
    
        public virtual ICollection<RoleAssignment> RoleAssignments { get; set; }
        public virtual ICollection<User> Users { get; set; }
    }
}
